name: ai-detector.yml
on: [ pull_request_target ]
jobs:
  detect-ai-gen-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run ai code detector
        uses: rbaucells/ai-code-detector-github-action@v1.5.0
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          token: ${{ github.token }}